version: '3'

services:
  check_backup_db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=kexpress
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
    volumes:
      - ./db/backups/latest:/docker-entrypoint-initdb.d:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=kexpress
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=postgres
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - "5432"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DATABASE_URL=postgres://postgres:qwerty@db/kexpress
      - POOL_MODE=session
      - MAX_CLIENT_CONN=500
    expose:
      - "5432"
    depends_on:
      - db
    ports:
      - "127.0.0.1:15432:5432"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "2"

  migrate_up:
    image: migrate/migrate
    volumes:
      - ./db/migrate:/migrations:ro
    command: "-path=/migrations/ -database postgres://postgres:qwerty@db:5432/kexpress?sslmode=disable up"
    depends_on:
      - db

  migrate_down:
    image: migrate/migrate
    volumes:
      - ./db/migrate:/migrations:ro
    command: "-path=/migrations/ -database postgres://postgres:qwerty@db:5432/kexpress?sslmode=disable down 1"
    depends_on:
      - db

  migrate_force:
    image: migrate/migrate
    volumes:
      - ./db/migrate:/migrations:ro
    command: "-path=/migrations/ -database postgres://postgres:qwerty@db:5432/kexpress?sslmode=disable force ${VERSION}"
    depends_on:
      - db

volumes:
  pg-data:
    driver: local
