CREATE TABLE characteristics (
  id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title varchar(1024) NOT NULL,
  created_at timestamp with time zone NOT NULL
);

ALTER TABLE characteristics ADD CONSTRAINT uniq_title_characteristics UNIQUE (title);
