CREATE TABLE sku_char_values (
  id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sku_id bigint NOT NULL,
  char_value_id bigint NOT NULL
);

CREATE UNIQUE INDEX uniq_sku_char_values ON sku_char_values (sku_id, char_value_id);

ALTER TABLE sku_char_values ADD CONSTRAINT fk_sku_char_values_sku_id
  FOREIGN KEY (sku_id) REFERENCES skus(id) ON DELETE CASCADE;

ALTER TABLE sku_char_values ADD CONSTRAINT fk_sku_char_values_char_value_id
  FOREIGN KEY (char_value_id) REFERENCES char_values(id) ON DELETE CASCADE;

ALTER TABLE skus DROP COLUMN char_value_id;

CREATE INDEX index_skus_product_id ON skus (product_id);
ALTER TABLE skus ADD CONSTRAINT fk_skus_product_id
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;

