CREATE TABLE products (
  id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  portal_id bigint NOT NULL,
  category_id bigint,
  seller_id bigint,
  orders_amount integer NOT NULL DEFAULT 0,
  reviews_amount integer NOT NULL DEFAULT 0,
  total_available_amount integer NOT NULL DEFAULT 0,
  rating numeric(3, 2) NOT NULL DEFAULT 0,
  category_title varchar(255),
  seller_title varchar(1024),
  title varchar(1024),
  description text,
  raw_json jsonb,
  created_at timestamp with time zone NOT NULL,
  parsed_at timestamp with time zone
);
