CREATE TABLE skus (
  id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id bigint NOT NULL,
  available_amount int NOT NULL DEFAULT 0,
  full_price numeric(12, 2) NOT NULL DEFAULT 0,
  purchase_price numeric(12, 2) NOT NULL DEFAULT 0,
  char_value_id bigint NOT NULL,
  created_at timestamp with time zone NOT NULL
);

COMMENT ON TABLE skus IS 'Stock keeping units';

ALTER TABLE skus ADD CONSTRAINT uniq_product_id_char_value_id UNIQUE
  (product_id, char_value_id);
