CREATE TABLE char_values (
  id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  char_id bigint NOT NULL,
  title varchar(1024) NOT NULL,
  value varchar(1024) NOT NULL,
  created_at timestamp with time zone NOT NULL
);

ALTER TABLE char_values ADD CONSTRAINT uniq_char_id_title_value UNIQUE
  (char_id, title, value);
