CREATE TABLE categories (
  id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  portal_id bigint NOT NULL,
  parent_id bigint NOT NULL DEFAULT 0,
  title varchar(255) NOT NULL,
  products_amount int NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone
);

ALTER TABLE categories ADD CONSTRAINT uniq_portal_id_categories UNIQUE (portal_id);
